<a href="https://colab.research.google.com/github/kyosshk/NN-DL-3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Employee Class
class Employee:
    num_of_employees = 0

    #initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    #Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)
#Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("Swathi", "Kothi", 50000, "Senior Software")
employee2 = Employee("Ashwini", "Alakuntla", 80000, "Manager")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Aishwarya", "Tagili", 50000, "Engineering", "FullTime")
fulltime2 = FulltimeEmployee("Sofeen", "Firdouse", 60000, "Marketing", "PartTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)

Total Employees: 4
Average Salary: 60000.0


In [2]:
import numpy as np
#generating a vector
vector = np.random.uniform(1, 20, 20)

#reshaping the vector into 4 * 5 matrix
matrix = vector.reshape(4, 5)

print("Original Matrix: \n",matrix)

#finding the index of the max element along axis = 1
indices = np.argmax(matrix, axis=1)

#Create a range of indices for each row
row_indices = np.arange(matrix.shape[0])

#Use advanced indexing to replace max values with 0
matrix[row_indices, indices] = 0

print("Resultant Matrix: \n",matrix)

Original Matrix: 
 [[12.53569429  4.51065381 13.15553157  2.60036115 18.44532693]
 [ 5.81065088 17.5195199   1.34389234 19.69222011 14.28907152]
 [11.01427796 14.57665818  5.51823621  2.55787483 12.47234616]
 [16.32542696  8.61448796 13.82733577  5.88717818  5.55980712]]
Resultant Matrix: 
 [[12.53569429  4.51065381 13.15553157  2.60036115  0.        ]
 [ 5.81065088 17.5195199   1.34389234  0.         14.28907152]
 [11.01427796  0.          5.51823621  2.55787483 12.47234616]
 [ 0.          8.61448796 13.82733577  5.88717818  5.55980712]]
